<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Messages.de.restext" />
    <None Remove="Resources\Messages.restext" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Messages.de.restext" />
    <EmbeddedResource Include="Resources\Messages.restext" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CodeBrix.Compression.MitLicenseForever" Version="1.0.48" />
    <PackageReference Include="CodeBrix.Imaging.ApacheLicenseForever" Version="1.0.48" />
  </ItemGroup>

</Project>
